#!/usr/bin/env bash
# =============================================================================
# 04-worker-join.sh — Phase 6: Worker Node Join
# =============================================================================
# Run this script on each WORKER NODE, AFTER 02-node-prep.sh.
#
# Two ways to use it:
#
#   Option A — Copy the join-command.sh generated by the control plane:
#     scp -i ~/.ssh/k8s-keypair.pem ubuntu@<CP_IP>:~/join-command.sh ~/join-command.sh
#     bash ~/join-command.sh
#
#   Option B — Run this script with the join flags from kubeadm init output:
#     scp -i ~/.ssh/k8s-keypair.pem 04-worker-join.sh ubuntu@<WORKER_IP>:~
#     ssh -i ~/.ssh/k8s-keypair.pem ubuntu@<WORKER_IP> \
#       "JOIN_TOKEN=<token> JOIN_HASH=<sha256:hash> CP_PRIVATE_IP=<ip> bash ~/04-worker-join.sh"
# =============================================================================

set -euo pipefail

echo "============================================================"
echo " Worker Node Join — $(hostname)"
echo "============================================================"

# ---------------------------------------------------------------------------
# Validate environment
# ---------------------------------------------------------------------------
: "${JOIN_TOKEN:?ERROR: JOIN_TOKEN is required. Get it from: kubeadm token create --print-join-command}"
: "${JOIN_HASH:?ERROR: JOIN_HASH is required (sha256:...). Get it from: kubeadm token create --print-join-command}"
: "${CP_PRIVATE_IP:?ERROR: CP_PRIVATE_IP is required (control plane private IP)}"

# ---------------------------------------------------------------------------
# Pre-join checks
# ---------------------------------------------------------------------------
echo ""
echo "--- Pre-join checks ---"

# Ensure kubelet is installed
if ! command -v kubeadm &>/dev/null; then
  echo "ERROR: kubeadm not found. Run 02-node-prep.sh first."
  exit 1
fi

# Ensure swap is off
if swapon --show | grep -q .; then
  echo "WARNING: Swap is on. Disabling..."
  sudo swapoff -a
fi

# Ensure containerd is running
if ! systemctl is-active containerd &>/dev/null; then
  echo "Starting containerd..."
  sudo systemctl start containerd
fi

echo "Pre-join checks passed."

# ---------------------------------------------------------------------------
# kubeadm join
# ---------------------------------------------------------------------------
echo ""
echo "--- Joining cluster at $CP_PRIVATE_IP:6443 ---"
sudo kubeadm join "${CP_PRIVATE_IP}:6443" \
  --token "$JOIN_TOKEN" \
  --discovery-token-ca-cert-hash "$JOIN_HASH"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "============================================================"
echo " Worker node joined successfully!"
echo ""
echo " Verify from the CONTROL PLANE with:"
echo "   kubectl get nodes -o wide"
echo ""
echo " This worker node should appear as Ready within ~60 seconds"
echo " after Calico networking initialises."
echo "============================================================"
